# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My_Foody_Body' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My_Foody_Body

  target 'My_Foody_BodyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My_Foody_BodyUITests' do
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
end
